//getting news from thewest api
export const FETCHING_NEWS = 'FETCHING_NEWS'
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS'
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE'

export const INCREASING_CURRENT_PAGE = 'INCREASING_CURRENT_PAGE'