//getting news from thewest api
export const FETCHING_NEWS = 'FETCHING_NEWS'
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS'
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE'

//getting tags from azure api
export const FETCHING_AZURE_AI = 'FETCHING_AZURE_AI'
export const FETCHING_AZURE_AI_SUCCESS = 'FETCHING_AZURE_AI_SUCCESS'
export const FETCHING_AZURE_AI_FAILURE = 'FETCHING_AZURE_AI_FAILURE'

export const INCREASING_CURRENT_PAGE = 'INCREASING_CURRENT_PAGE'