export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

//getting news from thewest api
export const FETCHING_NEWS = 'FETCHING_NEWS'
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS'
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE'